version: '3.3'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    # restart: always
    volumes:
      - ./storage/mongodb:/data/db
    command: ["mongod",  "--quiet", "--logpath", "/var/log/mongodb/mongod.log"]
    ports: 
    - 127.0.0.1:27017-27019:27017-27019
  mcrit-server:
    build: ./docker/mcrit/
    container_name: mcrit-server
    depends_on:
      - mongodb
    volumes:
      - ./config/:/opt/mcrit/mcrit/config/
    entrypoint:
      - /entry_server.sh
    ports: 
      - 127.0.0.1:8000:8000
  mcrit-worker:
    build: ./docker/mcrit/
    container_name: mcrit-worker
    depends_on:
      - mongodb
    volumes:
      - ./config/:/opt/mcrit/mcrit/config/
    entrypoint:
      - /entry_worker.sh
  mcritweb:
    build: ./docker/mcritweb/
    container_name: mcritweb
    depends_on:
      - mcrit-server
    volumes:
      - ./storage/mcritweb:/opt/mcritweb/instance
    entrypoint:
      - /entry_web_dev.sh
    ports: 
      - 127.0.0.1:5000:5000
