version: '3.3'

services:
  mongodb:
    image: mongo:${MONGO_TAG}
    container_name: mongodb
    # restart: always
    volumes:
      - ./storage/mongodb:/data/db
    command: ["mongod",  "--quiet", "--logpath", "/var/log/mongodb/mongod.log"]
    ports: 
    - 127.0.0.1:27017-27019:27017-27019
  mcrit-server:
    image: mcrit-server:${MCRIT_TAG}
    build:
      context: ./docker/mcrit/
      args:
        MCRIT_TAG: "${MCRIT_TAG}"
        MCRIT_BRANCH: "${MCRIT_BRANCH}"
    container_name: mcrit-server
    depends_on:
      - mongodb
    volumes:
      - ./config/:/opt/mcrit/mcrit/config/
    entrypoint:
      - /entry_server.sh
    ports: 
      - 127.0.0.1:8000:8000
  mcrit-worker:
    image: mcrit-worker:${MCRIT_TAG}
    build:
      context: ./docker/mcrit/
      args:
        MCRIT_TAG: "${MCRIT_TAG}"
        MCRIT_BRANCH: "${MCRIT_BRANCH}"
    container_name: mcrit-worker
    depends_on:
      - mongodb
    volumes:
      - ./config/:/opt/mcrit/mcrit/config/
    entrypoint:
      - /entry_worker.sh
  mcritweb:
    image: mcritweb:${MCRITWEB_TAG}
    build:
      context: ./docker/mcritweb/
      args:
        MCRITWEB_BRANCH: "${MCRITWEB_BRANCH}"
        MCRIT_TAG: "${MCRIT_TAG}"
    container_name: mcritweb
    depends_on:
      - mcrit-server
    volumes:
      - ./storage/mcritweb:/opt/mcritweb/instance
    entrypoint:
      - /entry_web_prod.sh
    ports: 
      - 127.0.0.1:5000:5000
  nginx:
    image: nginx:latest
    depends_on:
      - mcrit-server
      - mcrit-worker
      - mcritweb
    # restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/mcritweb_plain.conf:/etc/nginx/sites-enabled/mcritweb_plain.conf
      # alternatively, if deployment with TLS is desired, make sure to fill the files in ./nginx/ssl
      # - ./nginx/mcritweb_ssl.conf:/etc/nginx/sites-enabled/mcritweb_ssl.conf
      # - ./nginx/ssl:/opt/ssl_certificates
      - ./logs/nginx:/var/log/nginx
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
