version: '3.3'

services:
  mongodb:
    image: mongo:${MONGO_TAG}
    container_name: mongodb
    # restart: always
    volumes:
      - ./storage/mongodb:/data/db
    command: ["mongod",  "--quiet", "--logpath", "/var/log/mongodb/mongod.log"]
    ports: 
    - 127.0.0.1:27017-27019:27017-27019
  mcrit-server:
    image: mcrit-server:${MCRIT_TAG}
    build:
      context: ./docker/mcrit/
      args:
        MCRIT_TAG: "${MCRIT_TAG}"
        MCRIT_BRANCH: "${MCRIT_BRANCH}"
    container_name: mcrit-server
    depends_on:
      - mongodb
    volumes:
      - ./repositories/mcrit:/opt/mcrit/
      - ./config/:/opt/mcrit/mcrit/config/
    entrypoint:
      - /entry_server.sh
    ports: 
      - 127.0.0.1:8000:8000
  mcrit-worker:
    image: mcrit-worker:${MCRIT_TAG}
    build:
      context: ./docker/mcrit/
      args:
        MCRIT_TAG: "${MCRIT_TAG}"
        MCRIT_BRANCH: "${MCRIT_BRANCH}"
    container_name: mcrit-worker
    depends_on:
      - mongodb
    volumes:
      - ./repositories/mcrit:/opt/mcrit/
      - ./config/:/opt/mcrit/mcrit/config/
    entrypoint:
      - /entry_worker.sh
  mcritweb:
    image: mcritweb:${MCRITWEB_TAG}
    build:
      context: ./docker/mcritweb/
      args:
        MCRITWEB_BRANCH: "${MCRITWEB_BRANCH}"
        MCRIT_TAG: "${MCRIT_TAG}"
    container_name: mcritweb
    depends_on:
      - mcrit-server
    volumes:
      - ./repositories/mcritweb:/opt/mcritweb/
      - ./storage/mcritweb:/opt/mcritweb/instance
    entrypoint:
      - /entry_web_dev.sh
    ports: 
      - 127.0.0.1:5000:5000
