# Based on Workflow for main MCRIT and the workflow used in https://github.com/fkie-cad/cwe_checker
name: Build test

on: 
  push:
    branches:
      - main
  pull_request:

jobs: 
 
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build the docker image for MCRIT and MCRIT WEB 
        run: ./test_build.sh

      - name: Check functionality of the MCRIT image
        run: docker run --rm mcrit /entry_test.sh

