# Based on Workflow for main MCRIT and the workflow used in https://github.com/fkie-cad/cwe_checker
name: Build test

on: 
  push:
    branches:
      - main
  pull_request:

jobs: 
 
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          context: .

      - name: Build the docker image for MCRIT
        run: docker build -t mcrit docker/mcrit
      - name: Build the docker image for MCRIT WEB
        run: docker build -t mcritweb docker/mcritweb

      - name: Check functionality of the MCRIT image
        run: docker run --rm mcrit /entry_test.sh
